server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/management/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/management/(?<path>.*) , /$\{path}
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/accounts/(?<path>.*) , /$\{path}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
